### PR TITLE
Feature: TS allow expanded issuer section for the VC

### PR DESCRIPTION
**Pull request by vongohren**
According to section 4.5, example 9
https://www.w3.org/TR/vc-data-model/#example-9-usage-of-issuer-expanded-property

### CODE REVIEW

**Comment by simonas-notcat** [comment]
@awoie we are using `iss` field to specify the issuer. This is something specific to JWTs, right? Since this is `did-jwt-vc` library, we should not add an additional `issuer` field, or am I wrong here?

**Comment by awoie** [comment]
> @awoie we are using `iss` field to specify the issuer. This is something specific to JWTs, right? Since this is `did-jwt-vc` library, we should not add an additional `issuer` field, or am I wrong here?

Yes, using `iss` is the JWT-proof representation of VCs. In that case, you don't need an additional `issuer` property.

**Comment by simonas-notcat** [comment]
@vongohren why did you want to make this change? What problem are you trying to solve?

**Comment by awoie** [comment]
> @vongohren why did you want to make this change? What problem are you trying to solve?

I guess he wants to support claims about the issuer. The `iss` claim is not an object, it is a `SringOrUri`. If this needs to be added, one would need to add another property to the JWT containing that info. The JWT approach is a bit more restrictive than the  JSON-LD approach, i.e., single `credentialSubject`, `iss` is not an object etc.

**Comment by vongohren** [comment]
@simonas-notcat I want to utalize what the standard is talking about: https://www.w3.org/TR/vc-data-model/#example-9-usage-of-issuer-expanded-property, expanding the issuer field with metadata.

The current iss field is restricted as @awoie says, so this was my suggestion to be cater to that standard possiblity.  Much becasue the issuer is part of the VC data model that this lib wraps under vc. So yeah the iss is a JWT specific thing, but does not cater to the object possbilities

**Comment by awoie** [comment]
> @simonas-notcat I want to utalize what the standard is talking about: https://www.w3.org/TR/vc-data-model/#example-9-usage-of-issuer-expanded-property, expanding the issuer field with metadata.
> 
> The current iss field is restricted as @awoie says, so this was my suggestion to be cater to that standard possiblity. Much becasue the issuer is part of the VC data model that this lib wraps under vc. So yeah the iss is a JWT specific thing, but does not cater to the object possbilities

Unfortunately, this is a limitation of the JWT approach. It says, MUST use `iss` to represent `issuer`. That is to achieve interop with the JWT spec. So, I'm against the PR.

**Comment by vongohren** [comment]
@awoie I can understand that. But this feature the spec is talking about, is it important or else something did-jwt-vc will never support? The spec is a spec, but a lib can choose to implement only what it needs. But then this need is not doable like this, but will it ever be doable? Because of what you clarified?

**Comment by mirceanis** [comment]
There is also an issue of timing.
Even if the `iss` field is adapted to allow issuer metadata, the verification of any credential that uses it would fail because the underlying mechanism expects a DID.
So, the verification mechanism in did-jwt would need to be improved first.

Since issuer metadata is essentially a self-signed claim, we preferred to use separate VCs for this in the past, either embedded or linked.
This allows 3rd party issuers to make that metadata claim as well as being much more expressive.

That being said, I think it would be generally ok for the VC data type to have other arbitrary fields(`[x: string]: any`)

**Comment by mirceanis** [comment]
I'll close this since it's too early for it.
We can circle back to it once the verification libs are more up to speed with all the subtleties of the spec

**Pull request closed without merging**
